import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'game/game.dart';
import 'services/analytics_service.dart';
import 'services/ad_service.dart';
import 'services/storage_service.dart';

/// Batch-20260107-105243-puzzle-01 - Generated by GameFactory
/// 
/// A Flutter + Flame mobile game with analytics, ads, and level progression.
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Lock orientation to portrait
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
  
  // Initialize Firebase
  await Firebase.initializeApp();
  
  // Initialize services
  final analyticsService = AnalyticsService();
  final adService = AdService();
  final storageService = StorageService();
  
  await analyticsService.initialize();
  await adService.initialize();
  await storageService.initialize();
  
  runApp(
    MultiProvider(
      providers: [
        Provider<AnalyticsService>.value(value: analyticsService),
        Provider<AdService>.value(value: adService),
        Provider<StorageService>.value(value: storageService),
      ],
      child: const GameApp(),
    ),
  );
}

/// Main application widget
class GameApp extends StatelessWidget {
  const GameApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Batch-20260107-105243-puzzle-01',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.dark,
        ),
      ),
      home: const GameScreen(),
    );
  }
}
